# Dependabot will run on day 7 of each month at 03:49 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      day: 6
      timezone: "Europe/Berlin"
      cronjob: "49 3 7 * *"
    open-pull-requests-limit: 15
    assignees:
      - "Lenny"
    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      day: 6
      timezone: "Europe/Berlin"
      cronjob: "49 3 7 * *"
    open-pull-requests-limit: 15
    assignees:
      - "Lenny"
